# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
